### ISSUE TITLE
Open copr repo

### ISSUE THREAD

**Issue by CodedIsTaken** [dpejoh/Adwaita-colors#2]
Open a copr repo for fedora.

**Comment by dpejoh** [comment]
It will be published soon.

**Comment by CodedIsTaken** [comment]
Update: there has been no update on this news

so here's a better more easier method.

ask the guys of this repo to maintain a package for dissent https://terra.fyralabs.com/

**Comment by dpejoh** [comment]
Sorry man I really don't have time for this, I will do what you said, thanks!
