### ISSUE TITLE
Custom icons do not reflect accent color changes 

### ISSUE THREAD

**Issue by stormseal** [dpejoh/Adwaita-colors#6]
When using custom icons, such as custom folder icons, the icons do not automatically update to reflect changes to the accent color.

I understand how it might be problematic, but maybe limit it so it only changes custom icons chosen from adwaita colors

**Comment by stormseal** [comment]
Never mind, i saw there is already an issue open in the extension repo

**Comment by dpejoh** [comment]
The extension now supports custom folders
