### ISSUE TITLE
Integration with MoreWaita under Arch Linux

### ISSUE THREAD

**Issue by lic0san** [dpejoh/Adwaita-colors#8]
For some reason, the Automatic integration with MoreWaita under Arch Linux (using AUR packages) ceased to work after upgrade to morewaita-icon-theme 47.2-1. It worked seamlessly before that (using also Auto Adwaita Colors shell extension).

**Comment by dpejoh** [comment]
@somepaulo is the maintainer of the AUR package. I can't provide specific advice about AUR packages since I'm not familiar with Arch Linux. Could you paste the script output here? It's possible you didn't run the script with sudo, or the copy operation failed for some reason.

**Comment by somepaulo** [comment]
I'll double check this later tonight.

**Comment by somepaulo** [comment]
Just checked on my system and everything seems to work fine.  
The whole integration consists of adding `MoreWaita` into the `Inherits` line of each separate Adwaita-colors sub-theme, before `Adwaita`. This doesn't seem to break anything even if you don't have MoreWaita installed. Can you try reinstalling Adwaita-colors?

**Comment by dpejoh** [comment]
> The whole integration consists of adding `MoreWaita` into the `Inherits` line of each separate Adwaita-colors sub-theme's `index.theme` file, before `Adwaita`.

Read `MoreWaita.sh` script

**Comment by lic0san** [comment]
Indeed. I tried on another Arch computer, and even on another session on my own, and it works fine with latest AUR versions of adwaita-colors-icon-theme and morewaita-icon-theme. Something must be messed on my Gnome session, which appears not to take inheritance into consideration... Anyway, I'll try to figure this out, sorry for false alarm here, and thank you both for your work on these two collaborating icon themes :  it really adds some more harmony and refinement to Gnome !

**Comment by lic0san** [comment]
Just a quick follow-up note : I found the culprit was a duplicate installation of adwaita-colors in ~/.local/share/icons. Deleting everything in here restored the expected behavior of AUR packages.
