### ISSUE TITLE
Window minimize, maximize and close buttons for Qt apps are not Adwaita  

### ISSUE THREAD

**Issue by n3thshan** [dpejoh/Adwaita-colors#9]
### Description 
Best described in the following screenshots.

**Adwaita-colors:** 
![Screenshot From 2024-12-03 18-43-54](https://github.com/user-attachments/assets/bea36680-b024-49a7-b182-154199d10ed7)

**Adwaita (default):** 
![Screenshot From 2024-12-03 18-42-44](https://github.com/user-attachments/assets/22a7af84-a5e6-43f1-9f5b-5300fa7db051)

### Additional information

- GNOME version: 47
- Distro: Bluefin 41 (Silverblue)
- App provided in the screenshots: Anki Flatpak running on Wayland with the KDE Runtime

**Comment by dpejoh** [comment]
Fixed, check v2.4.1 release
